name: deploy-site

on:
  push:
    branches:
      - main
    paths:
      - "**"

defaults:
  run:
    working-directory: package

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install -g gatsby-cli
      - run: npm install -g gatsby
      - run: npm install
      - run: npm run build
        env:
          CONTENTFUL_API_KEY: ${{ secrets.CONTENTFUL_API_KEY }}

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync public s3://${{ secrets.AWS_S3_BUCKET_NAME }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - run: aws cloudfront --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
